# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': '\u0412\u0430\u0440\u0438\u0430\u0446\u0438\u044f', 'verbose_name_plural': '\u0412\u0430\u0440\u0438\u0430\u0446\u0438\u0438'},
        ),
    ]
