# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_search', '0002_auto_20160314_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_search.Recipe', verbose_name='\u0420\u0435\u0446\u0435\u043f\u0442'),
        ),
    ]
